FROM ubuntu:18.04
LABEL maintainer="diracdiego@gmail.com"
LABEL version="1.0"

RUN apt-get update && apt-get install -y \
    software-properties-common
RUN add-apt-repository ppa:team-gcc-arm-embedded/ppa
RUN apt-get update && apt-get install -y \
    gcc-arm-embedded \
    qemu-system-arm \
    qemu-user \
    gcc-multilib-arm-linux-gnueabi \
    binutils \
    llvm \
    clang \
    libc6-dev-i386

CMD ["/bin/bash"]